---
- name: Install MYSQL
  yum:
    name: mariadb-server
    state: present

- name: Install the Python MySQL Support Libraries
  yum: 
    name: MySQL-python
    state: latest

- name: start mysql server and enable it on reboot
  service: 
    name: mariadb 
    state: started
    enabled: "true"

- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

- name: update mysql root password for all root accounts
  mysql_user:
    login_user: root
    login_password: "{{ mysql_old_password }}"
    name: root
    host: "{{ item }}"
    password: "{{ mysql_new_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - localhost
    - 0.0.0.0

- name: Create a New Test DB called MyNewDB
  mysql_db: 
    name: MyNewDB
    state: present
    login_user: root 
    login_password: "{{ mysql_new_password }}"

